edge_test: replace deprecated "std::random_shuffle"
std::random_shuffle has been removed from C++ 17 standard [1].

GCC and its libstdc++ are pretty forgiving, but LLVM and its libc++
strictly adhere to the standard.

Note that the assert on self assignment of XEdge is removed, as
std::shuffle may do that [2]. C++ LWG is aware of this not-well
-defined behavior and recently approved a resolution [3], but that
would not take effect before C++ 23.

Fixes:

core/tests/edge_test.cpp:304:8: error: no member named 'random_shuffle' in namespace 'std'
  std::random_shuffle(all_edges.begin(), all_edges.end());
  ~~~~~^
core/tests/edge_test.cpp:373:8: error: no member named 'random_shuffle' in namespace 'std'
  std::random_shuffle(all_edges.begin(), all_edges.end());
  ~~~~~^
2 errors generated.

[1]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4190
[2]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85828
[3]: https://cplusplus.github.io/LWG/issue2839