sub_node: explicitly define copy constructor
Fixes:

core/sub_node.hpp:100:13: error: definition of implicit copy
constructor for 'Sub_node' is deprecated because it has a use
-declared copy assignment operator [-Werror,-Wdeprecated-copy]

  Sub_node &operator=(const Sub_node &) = delete;