elab: tests: drop test of removed Token_id_reference
Token_id_reference removed in 5148931b9b8ce9f78d82e79ece17e6f59b0e9e3f.

Fixes:

In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:376,
                 from elab/tests/elab_scanner_unit_test.cpp:11:
elab/tests/elab_scanner_unit_test.cpp:179:46: error: 'Token_id_reference' was not declared in this scope; did you mean 'Token_id_percent'?
  179 |     EXPECT_EQ(scanner.scan_get_token(i).tok, Token_id_reference);
      |                                              ^~~~~~~~~~~~~~~~~~