firrtl: drop deleted "firrtl_test_livehd.sh" target
Deleted by commit 2ceab1cf1903febf27603f4946f7b6b51546469a.

Fixes:

ERROR: livehd/inou/firrtl/BUILD:37:8: //inou/firrtl:firrtl_test_livehd.sh: missing input file '//inou/firrtl:tests/firrtl_test_livehd.sh'
ERROR: livehd/inou/firrtl/BUILD:37:8 1 input file(s) do not exist